/// OmniHub AI 模型目录数据（293 个，与网页版 js/ai-models.js 同步生成）
/// 生成时间：2026-07-31，勿手改，同步网页版时重新生成
part of 'ai_models.dart';

const List<Map<String, Object?>> kAiModelsData = [
  {'id': 'mimo-v2.5-pro', 'name': 'MiMo v2.5 Pro', 'provider': '小米 MiMo', 'desc': '小米 MiMo 旗舰推理模型，百万级上下文，数学与代码能力突出，支持深度思考。', 'ctx': 1024, 'thinking': true},
  {'id': 'mimo-v2.5-pro-ultraspeed', 'name': 'MiMo v2.5 Pro UltraSpeed', 'provider': '小米 MiMo', 'ctx': 1024, 'thinking': true},
  {'id': 'mimo-v2.5', 'name': 'MiMo v2.5', 'provider': '小米 MiMo', 'ctx': 128},
  {'id': 'mimo-v2.5-tts', 'name': 'MiMo v2.5 TTS', 'provider': '小米 MiMo', 'type': 'tts', 'note': '需内测资格', 'ctx': 128, 'stream': false},
  {'id': 'mimo-v2.5-tts-voiceclone', 'name': 'MiMo VoiceClone', 'provider': '小米 MiMo', 'type': 'voiceclone', 'note': '需内测资格', 'ctx': 128, 'stream': false},
  {'id': 'mimo-v2.5-tts-voicedesign', 'name': 'MiMo VoiceDesign', 'provider': '小米 MiMo', 'type': 'voicedesign', 'note': '需内测资格', 'ctx': 128, 'stream': false},
  {'id': 'mimo-v2.5-asr', 'name': 'MiMo ASR', 'provider': '小米 MiMo', 'type': 'asr', 'note': '需内测资格', 'ctx': 128, 'stream': false},
  {'id': 'deepseek-chat', 'name': 'DeepSeek Chat', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128},
  {'id': 'deepseek-reasoner', 'name': 'DeepSeek Reasoner', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128, 'thinking': true},
  {'id': 'deepseek-coder', 'name': 'DeepSeek Coder', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128},
  {'id': 'deepseek-v4-pro', 'name': 'DeepSeek V4 Pro', 'provider': 'DeepSeek', 'desc': 'DeepSeek 最新旗舰，推理、代码与Agent能力全面升级，支持识图与深度思考。', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'deepseek-v4-flash', 'name': 'DeepSeek V4 Flash', 'provider': 'DeepSeek', 'status': 'new', 'ctx': 1024, 'vision': true},
  {'id': 'deepseek-v3.2', 'name': 'DeepSeek V3.2', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128},
  {'id': 'deepseek-r1', 'name': 'DeepSeek R1', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128, 'thinking': true},
  {'id': 'qwen3.7-max', 'name': 'Qwen3.7-Max', 'provider': '通义千问', 'desc': '通义千问最强旗舰，全模态理解，支持深度思考与厂商联网搜索，百万上下文。', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'qwen3.6-max', 'name': 'Qwen3.6-Max', 'provider': '通义千问', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'qwen3.5-plus', 'name': 'Qwen3.5 Plus', 'provider': '通义千问', 'ctx': 1024, 'vision': true},
  {'id': 'qwen3-max', 'name': 'Qwen3-Max', 'provider': '通义千问', 'desc': '通义千问旗舰级超大模型，262K 长上下文，综合能力均衡。', 'ctx': 262},
  {'id': 'qwen-plus', 'name': '通义千问 Plus', 'provider': '通义千问', 'ctx': 1024, 'thinking': true},
  {'id': 'qwen2.5-72b', 'name': 'Qwen2.5-72B', 'provider': '通义千问', 'ctx': 128},
  {'id': 'qwen-max', 'name': '通义千问 Max', 'provider': '通义千问', 'ctx': 128, 'vision': true},
  {'id': 'qwen-turbo', 'name': '通义千问 Turbo', 'provider': '通义千问', 'ctx': 131, 'thinking': true},
  {'id': 'qwen-long', 'name': '通义千问 Long', 'provider': '通义千问', 'ctx': 10240},
  {'id': 'qwen-vl-max', 'name': '通义千问 VL Max', 'provider': '通义千问', 'ctx': 128, 'vision': true},
  {'id': 'qwen-coder-plus', 'name': '通义代码专家', 'provider': '通义千问', 'ctx': 128},
  {'id': 'qwen-vl-plus', 'name': '通义千问 VL Plus', 'provider': '通义千问', 'ctx': 128, 'vision': true},
  {'id': 'glm-5.2', 'name': 'GLM-5.2', 'provider': '智谱AI', 'desc': '智谱最新旗舰，Agent 与代码能力大幅增强，支持思考开关与联网检索。', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'glm-5.1', 'name': 'GLM-5.1', 'provider': '智谱AI', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'glm-5', 'name': 'GLM-5', 'provider': '智谱AI', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'glm-5-turbo', 'name': 'GLM-5-Turbo', 'provider': '智谱AI', 'ctx': 128, 'thinking': true},
  {'id': 'glm-4.7', 'name': 'GLM-4.7', 'provider': '智谱AI', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'glm-4.7-flashx', 'name': 'GLM-4.7-FlashX', 'provider': '智谱AI', 'ctx': 128},
  {'id': 'glm-4.7-flash', 'name': 'GLM-4.7-Flash', 'provider': '智谱AI', 'ctx': 128},
  {'id': 'glm-4-plus', 'name': 'GLM-4 Plus', 'provider': '智谱AI', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'glm-4-air', 'name': 'GLM-4 Air', 'provider': '智谱AI', 'ctx': 128},
  {'id': 'glm-4-flash', 'name': 'GLM-4 Flash', 'provider': '智谱AI', 'ctx': 128},
  {'id': 'glm-4v-plus', 'name': 'GLM-4V Plus', 'provider': '智谱AI', 'ctx': 128, 'vision': true},
  {'id': 'glm-4-long', 'name': 'GLM-4 Long', 'provider': '智谱AI', 'ctx': 1024},
  {'id': 'ernie-4.5-turbo', 'name': 'ERNIE 4.5 Turbo', 'provider': '文心一言', 'desc': '百度文心旗舰，多模态理解，中文创作与知识问答表现出色。', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'ernie-4.0-turbo-8k', 'name': 'ERNIE 4.0 Turbo', 'provider': '文心一言', 'ctx': 8, 'vision': true},
  {'id': 'ernie-speed', 'name': 'ERNIE Speed', 'provider': '文心一言', 'ctx': 128},
  {'id': 'ernie-lite', 'name': 'ERNIE Lite', 'provider': '文心一言', 'ctx': 128},
  {'id': 'ernie-3.5-8k', 'name': '文心一言 3.5', 'provider': '文心一言', 'ctx': 8},
  {'id': 'doubao-2.1-pro', 'name': 'Doubao 2.1 Pro', 'provider': '火山引擎', 'desc': '字节豆包旗舰，支持深度思考与识图，响应速度快，性价比高。', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'doubao-seed-1.6', 'name': 'Doubao-Seed 1.6', 'provider': '火山引擎', 'desc': '字节 Seed 1.6，自适应思考，多模态理解。', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'doubao-lite', 'name': 'Doubao Lite', 'provider': '火山引擎', 'ctx': 32},
  {'id': 'doubao-1.5-pro-256k', 'name': '豆包 1.5 Pro', 'provider': '火山引擎', 'ctx': 256, 'vision': true},
  {'id': 'doubao-1.5-lite-32k', 'name': '豆包 1.5 Lite', 'provider': '火山引擎', 'ctx': 32},
  {'id': 'doubao-pro-256k', 'name': '豆包 Pro', 'provider': '火山引擎', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'doubao-1.5-pro-32k', 'name': '豆包 1.5 Pro 32K', 'provider': '火山引擎', 'ctx': 32},
  {'id': 'doubao-vision', 'name': '豆包 Vision', 'provider': '火山引擎', 'ctx': 128, 'vision': true},
  {'id': 'hunyuan-turbos', 'name': 'HY 2.0 / 混元-TurboS', 'provider': '腾讯混元', 'desc': '腾讯混元 TurboS，快思考+深思考双模式，响应极快。', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'hunyuan-standard', 'name': '混元-Standard', 'provider': '腾讯混元', 'ctx': 128},
  {'id': 'hunyuan-lite-v2', 'name': '混元-Lite', 'provider': '腾讯混元', 'ctx': 128},
  {'id': 'hunyuan-3.0', 'name': '混元3.0', 'provider': '腾讯混元', 'desc': '腾讯混元新一代旗舰，多模态+深度思考，长文档处理能力强。', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'hunyuan-pro', 'name': '混元 Pro', 'provider': '腾讯混元', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'hunyuan-turbo', 'name': '混元 Turbo', 'provider': '腾讯混元', 'ctx': 128, 'vision': true},
  {'id': 'kimi-k2.5', 'name': 'Kimi K2.5', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'kimi-k2', 'name': 'Kimi K2', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'kimi-k2.7-code', 'name': 'Kimi K2.7 Code', 'provider': 'Kimi', 'status': 'new', 'ctx': 256, 'thinking': true},
  {'id': 'kimi-k2.6', 'name': 'Kimi K2.6', 'provider': 'Kimi', 'status': 'new', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'moonshot-v1-128k', 'name': 'Moonshot V1 128K', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 128},
  {'id': 'moonshot-v1-32k', 'name': 'Moonshot V1 32K', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 32},
  {'id': 'moonshot-v1-8k', 'name': 'Moonshot V1 8K', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 8},
  {'id': 'moonshot-v1-128k-vision-preview', 'name': 'Moonshot V1 128K Vision', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 128, 'vision': true},
  {'id': 'moonshot-v1-32k-vision-preview', 'name': 'Moonshot V1 32K Vision', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 32, 'vision': true},
  {'id': 'moonshot-v1-8k-vision-preview', 'name': 'Moonshot V1 8K Vision', 'provider': 'Kimi', 'status': 'deprecated', 'ctx': 8, 'vision': true},
  {'id': 'kimi-k3', 'name': 'Kimi K3', 'provider': 'Kimi', 'desc': '月之暗面最新旗舰，长文本与推理能力业界领先，支持联网搜索。', 'status': 'new', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'minimax-m3', 'name': 'MiniMax-M3', 'provider': 'MiniMax', 'desc': 'MiniMax 旗舰，百万上下文，Agent 任务与代码能力出色。', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'minimax-m2.7', 'name': 'MiniMax-M2.7', 'provider': 'MiniMax', 'ctx': 1024, 'thinking': true},
  {'id': 'minimax-m2.5', 'name': 'MiniMax-M2.5', 'provider': 'MiniMax', 'ctx': 1024, 'thinking': true},
  {'id': 'abab6.5s-chat', 'name': 'MiniMax M1', 'provider': 'MiniMax', 'status': 'deprecated', 'ctx': 1024},
  {'id': 'abab6.5g-chat', 'name': 'MiniMax M1 Pro', 'provider': 'MiniMax', 'status': 'deprecated', 'ctx': 128, 'vision': true},
  {'id': 'spark-max', 'name': '星火 Max', 'provider': '讯飞星火', 'desc': '讯飞星火旗舰，中文语音与文本能力兼备，支持识图。', 'ctx': 128, 'vision': true},
  {'id': 'spark-pro', 'name': '星火 Pro', 'provider': '讯飞星火', 'ctx': 128},
  {'id': 'spark-lite', 'name': '星火 Lite', 'provider': '讯飞星火', 'ctx': 128},
  {'id': 'skywork-math', 'name': '天工 天文', 'provider': '昆仑万维', 'ctx': 128},
  {'id': 'skywork-13b', 'name': '天工 13B', 'provider': '昆仑万维', 'ctx': 128},
  {'id': 'SenseChat-5', 'name': '日日新 SenseChat 5', 'provider': '商汤', 'desc': '商汤日日新 5.0，多模态理解，文科能力出色。', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'SenseChat-32K', 'name': '日日新 32K', 'provider': '商汤', 'ctx': 32},
  {'id': 'yi-large', 'name': 'Yi Large', 'provider': '零一万物', 'desc': '零一万物旗舰，中英双语能力均衡。', 'ctx': 128},
  {'id': 'yi-vision', 'name': 'Yi Vision', 'provider': '零一万物', 'ctx': 128, 'vision': true},
  {'id': 'yi-lightning', 'name': 'Yi Lightning', 'provider': '零一万物', 'ctx': 128},
  {'id': 'step-2-16k', 'name': 'Step 2 16K', 'provider': '阶跃星辰', 'desc': '阶跃星辰 Step 2 万亿参数 MoE 旗舰，支持识图。', 'ctx': 16, 'vision': true},
  {'id': 'step-2-mini', 'name': 'Step 2 Mini', 'provider': '阶跃星辰', 'ctx': 128},
  {'id': 'Baichuan4', 'name': '百川4', 'provider': '百川智能', 'desc': '百川智能第四代旗舰，中文知识问答能力强。', 'ctx': 128},
  {'id': 'gpt-5', 'name': 'GPT-5', 'provider': 'OpenAI', 'desc': 'OpenAI 第五代旗舰，内置深度推理，多模态理解。', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5-mini', 'name': 'GPT-5 Mini', 'provider': 'OpenAI', 'ctx': 400, 'vision': true, 'thinking': true},
  {'id': 'gpt-4.1', 'name': 'GPT-4.1', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true},
  {'id': 'gpt-4.1-mini', 'name': 'GPT-4.1 Mini', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true},
  {'id': 'gpt-4.1-nano', 'name': 'GPT-4.1 Nano', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true},
  {'id': 'gpt-4o', 'name': 'GPT-4o', 'provider': 'OpenAI', 'ctx': 128, 'vision': true},
  {'id': 'gpt-4o-mini', 'name': 'GPT-4o Mini', 'provider': 'OpenAI', 'ctx': 128, 'vision': true},
  {'id': 'o3', 'name': 'o3', 'provider': 'OpenAI', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'o3-mini', 'name': 'o3-mini', 'provider': 'OpenAI', 'ctx': 200, 'thinking': true},
  {'id': 'o4-mini', 'name': 'o4-mini', 'provider': 'OpenAI', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'o1', 'name': 'o1', 'provider': 'OpenAI', 'status': 'deprecated', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'gpt-4-turbo', 'name': 'GPT-4 Turbo', 'provider': 'OpenAI', 'status': 'deprecated', 'ctx': 128, 'vision': true},
  {'id': 'chatgpt-4o-latest', 'name': 'ChatGPT-4o Latest', 'provider': 'OpenAI', 'status': 'deprecated', 'ctx': 128, 'vision': true},
  {'id': 'gpt-5.6-sol', 'name': 'GPT-5.6 Sol', 'provider': 'OpenAI', 'desc': 'OpenAI 最新旗舰，全能型选手，推理、创作、代码均为顶级水准。', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.6-terra', 'name': 'GPT-5.6 Terra', 'provider': 'OpenAI', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.6-luna', 'name': 'GPT-5.6 Luna', 'provider': 'OpenAI', 'status': 'new', 'ctx': 400, 'vision': true, 'thinking': true},
  {'id': 'gpt-3.5-turbo-0125', 'name': 'GPT-3.5-Turbo-0125', 'provider': 'OpenAI', 'ctx': 16},
  {'id': 'gpt-4o-2024-08-06', 'name': 'GPT-4o-2024-08-06', 'provider': 'OpenAI', 'ctx': 128, 'vision': true},
  {'id': 'gpt-5.1', 'name': 'GPT-5.1', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.2', 'name': 'GPT-5.2', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.3-instant', 'name': 'GPT-5.3 Instant', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true},
  {'id': 'gpt-5.4', 'name': 'GPT-5.4', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.4-thinking', 'name': 'GPT-5.4 Thinking', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.4-pro', 'name': 'GPT-5.4 Pro', 'provider': 'OpenAI', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.5', 'name': 'GPT-5.5', 'provider': 'OpenAI', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gpt-5.6', 'name': 'GPT-5.6', 'provider': 'OpenAI', 'note': '价格待公布', 'status': 'new', 'ctx': 1536, 'vision': true, 'thinking': true},
  {'id': 'o1-preview', 'name': 'o1-preview', 'provider': 'OpenAI', 'ctx': 128, 'thinking': true},
  {'id': 'o1-mini', 'name': 'o1-mini', 'provider': 'OpenAI', 'ctx': 128, 'thinking': true},
  {'id': 'o5', 'name': 'o5', 'provider': 'OpenAI', 'note': '价格待公布', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'claude-opus-4.7', 'name': 'Claude Opus 4.7', 'provider': 'Anthropic', 'desc': 'Anthropic 旗舰，严谨可靠，擅长复杂分析与长文档。', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'claude-opus-4.6', 'name': 'Claude Opus 4.6', 'provider': 'Anthropic', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'claude-opus-4-20250514', 'name': 'Claude Opus 4', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200, 'vision': true},
  {'id': 'claude-sonnet-4.6', 'name': 'Claude Sonnet 4.6', 'provider': 'Anthropic', 'desc': 'Anthropic 主力模型，速度与能力平衡，代码能力一流。', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'claude-sonnet-4-20250514', 'name': 'Claude Sonnet 4', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200, 'vision': true},
  {'id': 'claude-sonnet-3.7', 'name': 'Claude Sonnet 3.7', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'claude-haiku-4.5', 'name': 'Claude Haiku 4.5', 'provider': 'Anthropic', 'ctx': 200, 'vision': true},
  {'id': 'claude-3-5-sonnet-20241022', 'name': 'Claude 3.5 Sonnet', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200, 'vision': true},
  {'id': 'claude-3-5-haiku-20241022', 'name': 'Claude 3.5 Haiku', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200, 'vision': true},
  {'id': 'claude-3-opus-20240229', 'name': 'Claude 3 Opus', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200, 'vision': true},
  {'id': 'claude-3-haiku-20240307', 'name': 'Claude 3 Haiku', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200},
  {'id': 'claude-fable-5', 'name': 'Claude Fable 5', 'provider': 'Anthropic', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'claude-sonnet-5', 'name': 'Claude Sonnet 5', 'provider': 'Anthropic', 'status': 'new', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'claude-opus-4-8', 'name': 'Claude Opus 4.8', 'provider': 'Anthropic', 'desc': 'Anthropic 最强模型，代码与写作能力业界标杆，超长上下文。', 'status': 'new', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'claude-2', 'name': 'Claude 2', 'provider': 'Anthropic', 'ctx': 100},
  {'id': 'claude-3-haiku', 'name': 'Claude 3 Haiku', 'provider': 'Anthropic', 'ctx': 200},
  {'id': 'claude-3-sonnet', 'name': 'Claude 3 Sonnet', 'provider': 'Anthropic', 'ctx': 200, 'vision': true},
  {'id': 'claude-3-opus', 'name': 'Claude 3 Opus', 'provider': 'Anthropic', 'ctx': 200, 'vision': true},
  {'id': 'claude-3-5-sonnet', 'name': 'Claude 3.5 Sonnet', 'provider': 'Anthropic', 'ctx': 200, 'vision': true},
  {'id': 'claude-3-5-haiku', 'name': 'Claude 3.5 Haiku', 'provider': 'Anthropic', 'ctx': 200},
  {'id': 'claude-sonnet-4', 'name': 'Claude Sonnet 4', 'provider': 'Anthropic', 'ctx': 200, 'vision': true},
  {'id': 'claude-sonnet-4-5', 'name': 'Claude Sonnet 4.5', 'provider': 'Anthropic', 'ctx': 200, 'vision': true},
  {'id': 'claude-opus-4-1', 'name': 'Claude Opus 4.1', 'provider': 'Anthropic', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'claude-opus-4-5', 'name': 'Claude Opus 4.5', 'provider': 'Anthropic', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'claude-mythos-5', 'name': 'Claude Mythos 5', 'provider': 'Anthropic', 'note': '需审核访问', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gemini-3.1-pro', 'name': 'Gemini 3.1 Pro', 'provider': 'Google', 'desc': 'Google 最新旗舰，原生多模态，百万上下文，内置联网搜索。', 'ctx': 200, 'vision': true, 'thinking': true},
  {'id': 'gemini-3.1-flash-lite', 'name': 'Gemini 3.1 Flash-Lite', 'provider': 'Google', 'status': 'new', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-2.5-pro', 'name': 'Gemini 2.5 Pro', 'provider': 'Google', 'desc': 'Google 高性能模型，思考模式加持，多模态理解出色。', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'gemini-2.5-flash', 'name': 'Gemini 2.5 Flash', 'provider': 'Google', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-2.5-flash-lite', 'name': 'Gemini 2.5 Flash-Lite', 'provider': 'Google', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-2.0-flash', 'name': 'Gemini 2.0 Flash', 'provider': 'Google', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-1.5-pro', 'name': 'Gemini 1.5 Pro', 'provider': 'Google', 'ctx': 128, 'vision': true},
  {'id': 'gemini-1.5-flash', 'name': 'Gemini 1.5 Flash', 'provider': 'Google', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-3.5-flash', 'name': 'Gemini 3.5 Flash', 'provider': 'Google', 'status': 'new', 'ctx': 1024, 'vision': true},
  {'id': 'bard', 'name': 'Bard', 'provider': 'Google', 'ctx': 8},
  {'id': 'gemini-1.0-nano', 'name': 'Gemini 1.0 Nano', 'provider': 'Google', 'ctx': 32},
  {'id': 'gemini-1.5-pro-002', 'name': 'Gemini 1.5 Pro-002', 'provider': 'Google', 'ctx': 2048, 'vision': true},
  {'id': 'gemini-1.5-flash-002', 'name': 'Gemini 1.5 Flash-002', 'provider': 'Google', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-2.0-flash-exp', 'name': 'Gemini 2.0 Flash Exp', 'provider': 'Google', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-2.0-flash-lite', 'name': 'Gemini 2.0 Flash-Lite', 'provider': 'Google', 'ctx': 1024, 'vision': true},
  {'id': 'gemini-2.0-flash-thinking-exp', 'name': 'Gemini 2.0 Flash Thinking', 'provider': 'Google', 'ctx': 32, 'thinking': true},
  {'id': 'grok-4.5', 'name': 'Grok 4.5', 'provider': 'xAI', 'desc': 'xAI 旗舰，实时信息获取能力强，推理与幽默感兼备。', 'status': 'new', 'ctx': 500, 'vision': true, 'thinking': true},
  {'id': 'grok-4.3', 'name': 'Grok 4.3', 'provider': 'xAI', 'status': 'new', 'ctx': 1024, 'vision': true, 'thinking': true},
  {'id': 'grok-4.20', 'name': 'Grok 4.20', 'provider': 'xAI', 'desc': 'xAI 高性能版本，支持深度思考，实时联网。', 'ctx': 2048, 'vision': true, 'thinking': true},
  {'id': 'grok-4.1-fast', 'name': 'Grok 4.1 Fast', 'provider': 'xAI', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'grok-code-fast-1', 'name': 'Grok-code-fast-1', 'provider': 'xAI', 'ctx': 256, 'thinking': true},
  {'id': 'grok-2', 'name': 'Grok 2', 'provider': 'xAI', 'status': 'deprecated', 'ctx': 128},
  {'id': 'grok-3', 'name': 'Grok 3', 'provider': 'xAI', 'ctx': 131, 'vision': true, 'thinking': true},
  {'id': 'grok-3-mini', 'name': 'Grok 3 Mini', 'provider': 'xAI', 'ctx': 131, 'vision': true, 'thinking': true},
  {'id': 'grok-2-1212', 'name': 'Grok 2 GA', 'provider': 'xAI', 'ctx': 128},
  {'id': 'grok-2-vision-1212', 'name': 'Grok 2 Vision', 'provider': 'xAI', 'ctx': 32, 'vision': true},
  {'id': 'grok-3-fast', 'name': 'Grok 3 Fast', 'provider': 'xAI', 'ctx': 131, 'vision': true, 'thinking': true},
  {'id': 'grok-3-mini-fast', 'name': 'Grok 3 Mini Fast', 'provider': 'xAI', 'ctx': 131, 'vision': true, 'thinking': true},
  {'id': 'grok-3-beta', 'name': 'Grok 3 Beta', 'provider': 'xAI', 'ctx': 131, 'vision': true, 'thinking': true},
  {'id': 'grok-4', 'name': 'Grok 4', 'provider': 'xAI', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'grok-4-heavy', 'name': 'Grok 4 Heavy', 'provider': 'xAI', 'ctx': 256, 'vision': true, 'thinking': true},
  {'id': 'grok-4-fast', 'name': 'Grok 4 Fast', 'provider': 'xAI', 'ctx': 2048, 'vision': true, 'thinking': true},
  {'id': 'grok-4.1', 'name': 'Grok 4.1', 'provider': 'xAI', 'ctx': 2048, 'vision': true, 'thinking': true},
  {'id': 'grok-4-1-fast-reasoning', 'name': 'Grok 4.1 Fast Reasoning', 'provider': 'xAI', 'ctx': 2048, 'vision': true, 'thinking': true},
  {'id': 'grok-4-1-fast-non-reasoning', 'name': 'Grok 4.1 Fast Non-Reasoning', 'provider': 'xAI', 'ctx': 2048, 'vision': true},
  {'id': 'grok-4.20-multi-agent', 'name': 'Grok 4.20 Multi-Agent', 'provider': 'xAI', 'ctx': 2048, 'vision': true, 'thinking': true},
  {'id': 'grok-4.20-reasoning', 'name': 'Grok 4.20 Reasoning', 'provider': 'xAI', 'ctx': 2048, 'vision': true, 'thinking': true},
  {'id': 'grok-4.20-non-reasoning', 'name': 'Grok 4.20 Non-Reasoning', 'provider': 'xAI', 'ctx': 2048, 'vision': true},
  {'id': 'grok-build-0.1', 'name': 'Grok Build 0.1', 'provider': 'xAI', 'status': 'new', 'ctx': 256, 'thinking': true},
  {'id': 'mistral-medium-3.5', 'name': 'Mistral Medium 3.5', 'provider': 'Mistral', 'ctx': 128, 'vision': true},
  {'id': 'mistral-large-3', 'name': 'Mistral Large 3', 'provider': 'Mistral', 'desc': 'Mistral 欧洲旗舰，多语言能力出色，支持识图。', 'ctx': 128, 'vision': true},
  {'id': 'mistral-small-4', 'name': 'Mistral Small 4', 'provider': 'Mistral', 'ctx': 128, 'vision': true},
  {'id': 'codestral-latest', 'name': 'Codestral', 'provider': 'Mistral', 'ctx': 128},
  {'id': 'devstral-2', 'name': 'Devstral 2', 'provider': 'Mistral', 'ctx': 128},
  {'id': 'ministral-3b', 'name': 'Ministral 3B', 'provider': 'Mistral', 'ctx': 32},
  {'id': 'mistral-large-latest', 'name': 'Mistral Large', 'provider': 'Mistral', 'ctx': 128, 'vision': true},
  {'id': 'mistral-small-latest', 'name': 'Mistral Small', 'provider': 'Mistral', 'ctx': 128, 'vision': true},
  {'id': 'pixtral-large-latest', 'name': 'Pixtral Large', 'provider': 'Mistral', 'ctx': 128, 'vision': true},
  {'id': 'llama-4-maverick', 'name': 'Llama 4 Maverick', 'provider': 'Meta', 'desc': 'Meta 开源旗舰，原生多模态 MoE 架构，可自由部署。', 'ctx': 128, 'vision': true, 'thinking': true},
  {'id': 'llama-4-scout', 'name': 'Llama 4 Scout', 'provider': 'Meta', 'ctx': 128, 'vision': true},
  {'id': 'llama-3.3-70b', 'name': 'Llama 3.3 70B', 'provider': 'Meta', 'ctx': 128},
  {'id': 'llama-3.2-90b-vision', 'name': 'Llama 3.2 90B Vision', 'provider': 'Meta', 'ctx': 128, 'vision': true},
  {'id': 'llama-3.2-11b-vision', 'name': 'Llama 3.2 11B Vision', 'provider': 'Meta', 'ctx': 128, 'vision': true},
  {'id': 'llama-3.1-405b', 'name': 'Llama 3.1 405B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 128},
  {'id': 'llama-3.1-70b', 'name': 'Llama 3.1 70B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 128},
  {'id': 'llama-3-8b', 'name': 'Llama 3 8B', 'provider': 'Meta', 'ctx': 8},
  {'id': 'llama-3-70b', 'name': 'Llama 3 70B', 'provider': 'Meta', 'ctx': 8},
  {'id': 'command-r-plus', 'name': 'Command R+', 'provider': 'Cohere', 'status': 'deprecated', 'ctx': 128},
  {'id': 'command-r', 'name': 'Command R', 'provider': 'Cohere', 'status': 'deprecated', 'ctx': 128},
  {'id': 'command-a', 'name': 'Command A', 'provider': 'Cohere', 'desc': 'Cohere 企业级旗舰，RAG 与工具调用能力专精。', 'ctx': 128, 'vision': true},
  {'id': 'command-r7b', 'name': 'Command R7B', 'provider': 'Cohere', 'ctx': 128},
  {'id': 'llama-3.1-70b-versatile', 'name': 'Llama 3.1 70B (Groq)', 'provider': 'Groq', 'status': 'deprecated', 'ctx': 128},
  {'id': 'mixtral-8x7b-32768', 'name': 'Mixtral 8x7B (Groq)', 'provider': 'Groq', 'status': 'deprecated', 'ctx': 32},
  {'id': 'llama-3.3-70b-versatile', 'name': 'Llama 3.3 70B (Groq)', 'provider': 'Groq', 'ctx': 128},
  {'id': 'mimo-v2', 'name': 'MiMo v2', 'provider': '小米 MiMo', 'status': 'deprecated', 'ctx': 128},
  {'id': 'mimo-v2-pro', 'name': 'MiMo v2 Pro', 'provider': '小米 MiMo', 'status': 'deprecated', 'ctx': 256, 'thinking': true},
  {'id': 'gpt-4', 'name': 'GPT-4', 'provider': 'OpenAI', 'desc': 'OpenAI 划时代模型，2023 年发布，奠定了大模型应用浪潮。', 'status': 'deprecated', 'ctx': 8},
  {'id': 'gpt-3.5-turbo', 'name': 'GPT-3.5 Turbo', 'provider': 'OpenAI', 'desc': 'ChatGPT 初代同款，轻快实用，曾是全球调用量最大的模型。', 'status': 'deprecated', 'ctx': 4},
  {'id': 'gpt-3', 'name': 'GPT-3', 'provider': 'OpenAI', 'status': 'deprecated', 'ctx': 2},
  {'id': 'gpt-3.5-turbo-16k', 'name': 'GPT-3.5-Turbo-16K', 'provider': 'OpenAI', 'status': 'deprecated', 'ctx': 16},
  {'id': 'gpt-4-32k', 'name': 'GPT-4-32K', 'provider': 'OpenAI', 'status': 'deprecated', 'ctx': 32},
  {'id': 'claude-2.1', 'name': 'Claude 2.1', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 200},
  {'id': 'claude-2.0', 'name': 'Claude 2.0', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 100},
  {'id': 'claude-instant-1.2', 'name': 'Claude Instant 1.2', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 100},
  {'id': 'claude-1', 'name': 'Claude 1', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 9},
  {'id': 'claude-instant-1', 'name': 'Claude Instant 1', 'provider': 'Anthropic', 'status': 'deprecated', 'ctx': 9},
  {'id': 'gemini-1.0-pro', 'name': 'Gemini 1.0 Pro', 'provider': 'Google', 'status': 'deprecated', 'ctx': 32},
  {'id': 'gemini-1.5-flash-8b', 'name': 'Gemini 1.5 Flash-8B', 'provider': 'Google', 'status': 'deprecated', 'ctx': 1024, 'vision': true},
  {'id': 'palm-2', 'name': 'PaLM 2', 'provider': 'Google', 'status': 'deprecated', 'ctx': 8},
  {'id': 'palm-2-chat', 'name': 'PaLM 2 Chat', 'provider': 'Google', 'status': 'deprecated', 'ctx': 8},
  {'id': 'gemini-1.0-ultra', 'name': 'Gemini 1.0 Ultra', 'provider': 'Google', 'status': 'deprecated', 'ctx': 32},
  {'id': 'gemini-2.0-pro-exp', 'name': 'Gemini 2.0 Pro Exp', 'provider': 'Google', 'status': 'deprecated', 'ctx': 2048, 'vision': true},
  {'id': 'deepseek-v2.5', 'name': 'DeepSeek V2.5', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128},
  {'id': 'deepseek-v2', 'name': 'DeepSeek V2', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128},
  {'id': 'deepseek-coder-v2', 'name': 'DeepSeek Coder V2', 'provider': 'DeepSeek', 'status': 'deprecated', 'ctx': 128},
  {'id': 'qwen2.5-max', 'name': 'Qwen2.5-Max', 'provider': '通义千问', 'status': 'deprecated', 'ctx': 128},
  {'id': 'qwen2-72b-instruct', 'name': 'Qwen2-72B', 'provider': '通义千问', 'status': 'deprecated', 'ctx': 128},
  {'id': 'qwen1.5-72b-chat', 'name': 'Qwen1.5-72B', 'provider': '通义千问', 'status': 'deprecated', 'ctx': 32},
  {'id': 'glm-4-0520', 'name': 'GLM-4 0520', 'provider': '智谱AI', 'status': 'deprecated', 'ctx': 128},
  {'id': 'glm-4-airx', 'name': 'GLM-4 AirX', 'provider': '智谱AI', 'status': 'deprecated', 'ctx': 8},
  {'id': 'glm-3-turbo', 'name': 'GLM-3 Turbo', 'provider': '智谱AI', 'status': 'deprecated', 'ctx': 128},
  {'id': 'ernie-4.0-8k', 'name': 'ERNIE 4.0', 'provider': '文心一言', 'status': 'deprecated', 'ctx': 8},
  {'id': 'ernie-bot-turbo', 'name': 'ERNIE Bot Turbo', 'provider': '文心一言', 'status': 'deprecated', 'ctx': 8},
  {'id': 'doubao-pro-4k', 'name': '豆包 Pro 4K', 'provider': '火山引擎', 'status': 'deprecated', 'ctx': 4},
  {'id': 'doubao-pro-32k', 'name': '豆包 Pro 32K', 'provider': '火山引擎', 'status': 'deprecated', 'ctx': 32},
  {'id': 'doubao-lite-4k', 'name': '豆包 Lite 4K', 'provider': '火山引擎', 'status': 'deprecated', 'ctx': 4},
  {'id': 'hunyuan-large', 'name': '混元 Large', 'provider': '腾讯混元', 'status': 'deprecated', 'ctx': 128},
  {'id': 'abab6-chat', 'name': 'ABAB 6', 'provider': 'MiniMax', 'status': 'deprecated', 'ctx': 8},
  {'id': 'abab5.5-chat', 'name': 'ABAB 5.5', 'provider': 'MiniMax', 'status': 'deprecated', 'ctx': 16},
  {'id': 'spark-v3.5', 'name': '星火 v3.5', 'provider': '讯飞星火', 'status': 'deprecated', 'ctx': 8},
  {'id': 'spark-v3.0', 'name': '星火 v3.0', 'provider': '讯飞星火', 'status': 'deprecated', 'ctx': 8},
  {'id': 'spark-v2.0', 'name': '星火 v2.0', 'provider': '讯飞星火', 'status': 'deprecated', 'ctx': 8},
  {'id': 'SenseChat-128K', 'name': '日日新 128K', 'provider': '商汤', 'status': 'deprecated', 'ctx': 128},
  {'id': 'yi-34b-chat', 'name': 'Yi-34B Chat', 'provider': '零一万物', 'status': 'deprecated', 'ctx': 4},
  {'id': 'yi-medium', 'name': 'Yi Medium', 'provider': '零一万物', 'status': 'deprecated', 'ctx': 16},
  {'id': 'step-1-32k', 'name': 'Step 1 32K', 'provider': '阶跃星辰', 'status': 'deprecated', 'ctx': 32},
  {'id': 'step-1v-32k', 'name': 'Step 1V 32K', 'provider': '阶跃星辰', 'status': 'deprecated', 'ctx': 32, 'vision': true},
  {'id': 'Baichuan3-Turbo', 'name': '百川3 Turbo', 'provider': '百川智能', 'status': 'deprecated', 'ctx': 32},
  {'id': 'Baichuan2-53B', 'name': '百川2 53B', 'provider': '百川智能', 'status': 'deprecated', 'ctx': 8},
  {'id': 'llama-3-70b-instruct', 'name': 'Llama 3 70B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 8},
  {'id': 'llama-3-8b-instruct', 'name': 'Llama 3 8B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 8},
  {'id': 'llama-2-70b-chat', 'name': 'Llama 2 70B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 4},
  {'id': 'llama-1-7b', 'name': 'Llama 1 7B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 2},
  {'id': 'llama-1-13b', 'name': 'Llama 1 13B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 2},
  {'id': 'llama-1-33b', 'name': 'Llama 1 33B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 2},
  {'id': 'llama-1-65b', 'name': 'Llama 1 65B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 2},
  {'id': 'llama-2-7b', 'name': 'Llama 2 7B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 4},
  {'id': 'llama-2-13b', 'name': 'Llama 2 13B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 4},
  {'id': 'llama-2-70b', 'name': 'Llama 2 70B', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 4},
  {'id': 'llama-2-code-*', 'name': 'Llama 2 Code', 'provider': 'Meta', 'status': 'deprecated', 'ctx': 4},
  {'id': 'mistral-large-2407', 'name': 'Mistral Large 2', 'provider': 'Mistral', 'status': 'deprecated', 'ctx': 128},
  {'id': 'mixtral-8x22b-instruct', 'name': 'Mixtral 8x22B', 'provider': 'Mistral', 'status': 'deprecated', 'ctx': 64},
  {'id': 'mixtral-8x7b-instruct', 'name': 'Mixtral 8x7B', 'provider': 'Mistral', 'status': 'deprecated', 'ctx': 32},
  {'id': 'mistral-7b-instruct', 'name': 'Mistral 7B', 'provider': 'Mistral', 'status': 'deprecated', 'ctx': 32},
  {'id': 'command', 'name': 'Command', 'provider': 'Cohere', 'status': 'deprecated', 'ctx': 4},
  {'id': 'command-light', 'name': 'Command Light', 'provider': 'Cohere', 'status': 'deprecated', 'ctx': 4},
  {'id': 'grok-beta', 'name': 'Grok Beta', 'provider': 'xAI', 'status': 'deprecated', 'ctx': 128},
  {'id': 'grok-2-mini', 'name': 'Grok 2 Mini', 'provider': 'xAI', 'status': 'deprecated', 'ctx': 128},
  {'id': 'grok-1', 'name': 'Grok 1', 'provider': 'xAI', 'status': 'deprecated', 'ctx': 8},
  {'id': 'grok-1.5', 'name': 'Grok 1.5', 'provider': 'xAI', 'status': 'deprecated', 'ctx': 128},
  {'id': 'gemma2-9b-it', 'name': 'Gemma 2 9B (Groq)', 'provider': 'Groq', 'status': 'deprecated', 'ctx': 8},
  {'id': 'llama-3.1-8b-instant', 'name': 'Llama 3.1 8B (Groq)', 'provider': 'Groq', 'ctx': 128},
  {'id': 'gpt-5.5-edu', 'name': 'GPT-5.5 Edu', 'provider': 'OpenAI', 'type': 'chat', 'category': 'education', 'status': 'new', 'ctx': 128},
  {'id': 'claude-sonnet-5-edu', 'name': 'Claude Sonnet 5 Edu', 'provider': 'Anthropic', 'type': 'chat', 'category': 'education', 'status': 'new', 'ctx': 200},
  {'id': 'qwen-edu-plus', 'name': '通义千问教育版', 'provider': '通义千问', 'type': 'chat', 'category': 'education', 'status': 'new', 'ctx': 128},
  {'id': 'glm-edu-4', 'name': '智谱教育助手', 'provider': '智谱AI', 'type': 'chat', 'category': 'education', 'ctx': 128},
  {'id': 'kimi-edu-k3', 'name': 'Kimi教育K3', 'provider': 'Kimi', 'type': 'chat', 'category': 'education', 'status': 'new', 'ctx': 256},
  {'id': 'gpt-5.5-med', 'name': 'GPT-5.5 Medical', 'provider': 'OpenAI', 'type': 'chat', 'category': 'medical', 'status': 'new', 'ctx': 128},
  {'id': 'claude-opus-4-med', 'name': 'Claude Opus 4 Medical', 'provider': 'Anthropic', 'type': 'chat', 'category': 'medical', 'status': 'new', 'ctx': 200},
  {'id': 'qwen-med-v2', 'name': '通义千问医疗版', 'provider': '通义千问', 'type': 'chat', 'category': 'medical', 'status': 'new', 'ctx': 128, 'vision': true},
  {'id': 'hunyuan-med-2', 'name': '腾讯混元医疗', 'provider': '腾讯混元', 'type': 'chat', 'category': 'medical', 'ctx': 32},
  {'id': 'baichuan-med-7', 'name': '百川医疗7B', 'provider': '百川智能', 'type': 'chat', 'category': 'medical', 'ctx': 32},
  {'id': 'gpt-5.5-law', 'name': 'GPT-5.5 Legal', 'provider': 'OpenAI', 'type': 'chat', 'category': 'legal', 'status': 'new', 'ctx': 128},
  {'id': 'claude-sonnet-5-law', 'name': 'Claude Sonnet 5 Legal', 'provider': 'Anthropic', 'type': 'chat', 'category': 'legal', 'status': 'new', 'ctx': 200},
  {'id': 'qwen-law-plus', 'name': '通义千问法律版', 'provider': '通义千问', 'type': 'chat', 'category': 'legal', 'status': 'new', 'ctx': 128},
  {'id': 'ernie-law-4', 'name': '文心法律4.0', 'provider': '文心一言', 'type': 'chat', 'category': 'legal', 'ctx': 128},
  {'id': 'kimi-law-k3', 'name': 'Kimi法律K3', 'provider': 'Kimi', 'type': 'chat', 'category': 'legal', 'status': 'new', 'ctx': 256},
  {'id': 'gpt-5.5-fin', 'name': 'GPT-5.5 Finance', 'provider': 'OpenAI', 'type': 'chat', 'category': 'finance', 'status': 'new', 'ctx': 128},
  {'id': 'claude-opus-4-fin', 'name': 'Claude Opus 4 Finance', 'provider': 'Anthropic', 'type': 'chat', 'category': 'finance', 'status': 'new', 'ctx': 200},
  {'id': 'qwen-fin-plus', 'name': '通义千问金融版', 'provider': '通义千问', 'type': 'chat', 'category': 'finance', 'status': 'new', 'ctx': 128},
  {'id': 'glm-fin-4', 'name': '智谱金融助手', 'provider': '智谱AI', 'type': 'chat', 'category': 'finance', 'ctx': 128},
  {'id': 'doubao-fin-pro', 'name': '豆包金融Pro', 'provider': '火山引擎', 'type': 'chat', 'category': 'finance', 'status': 'new', 'ctx': 256},
  {'id': 'deepseek-fin-v4', 'name': 'DeepSeek金融V4', 'provider': 'DeepSeek', 'type': 'chat', 'category': 'finance', 'ctx': 64},
];

/// 六榜单离线参考数据（与网页版 js/leaderboard-data.js FALLBACK 同步）
const Map<String, List<Map<String, Object>>> kLeaderboardData = {
  'overall': [
    {'id': 'gpt-4o', 'name': 'GPT-4o', 'provider': 'OpenAI', 'score': 89.3},
    {'id': 'claude-sonnet-3.7', 'name': 'Claude 3.7 Sonnet', 'provider': 'Anthropic', 'score': 88.7},
    {'id': 'gemini-2.5-pro', 'name': 'Gemini 2.5 Pro', 'provider': 'Google', 'score': 88.1},
    {'id': 'deepseek-v4-pro', 'name': 'DeepSeek V4 Pro', 'provider': 'DeepSeek', 'score': 86.5},
    {'id': 'kimi-k2', 'name': 'Kimi K2', 'provider': 'Kimi', 'score': 85.2},
    {'id': 'qwen3-max', 'name': 'Qwen3-Max', 'provider': '通义千问', 'score': 84.6},
    {'id': 'llama-4-maverick', 'name': 'Llama 4 Maverick', 'provider': 'Meta', 'score': 83.1},
    {'id': 'mistral-large-3', 'name': 'Mistral Large 3', 'provider': 'Mistral', 'score': 81.4},
    {'id': 'grok-4', 'name': 'Grok 4', 'provider': 'xAI', 'score': 83.8},
    {'id': 'glm-5.2', 'name': 'GLM-5.2', 'provider': '智谱AI', 'score': 82.6},
  ],
  'coding': [
    {'id': 'claude-sonnet-3.7', 'name': 'Claude 3.7 Sonnet', 'provider': 'Anthropic', 'score': 62.3},
    {'id': 'gpt-4o', 'name': 'GPT-4o', 'provider': 'OpenAI', 'score': 58.9},
    {'id': 'gemini-2.5-pro', 'name': 'Gemini 2.5 Pro', 'provider': 'Google', 'score': 57.6},
    {'id': 'deepseek-v4-pro', 'name': 'DeepSeek V4 Pro', 'provider': 'DeepSeek', 'score': 56.8},
    {'id': 'kimi-k2.7-code', 'name': 'Kimi K2.7 Code', 'provider': 'Kimi', 'score': 55.4},
    {'id': 'qwen3-max', 'name': 'Qwen3-Max', 'provider': '通义千问', 'score': 54.1},
    {'id': 'grok-code-fast-1', 'name': 'Grok Code Fast 1', 'provider': 'xAI', 'score': 52.7},
    {'id': 'glm-5.2', 'name': 'GLM-5.2', 'provider': '智谱AI', 'score': 51.9},
    {'id': 'codestral-latest', 'name': 'Codestral', 'provider': 'Mistral', 'score': 50.2},
    {'id': 'llama-4-maverick', 'name': 'Llama 4 Maverick', 'provider': 'Meta', 'score': 48.6},
  ],
  'longctx': [
    {'id': 'gemini-2.5-pro', 'name': 'Gemini 2.5 Pro', 'provider': 'Google', 'score': 91.5},
    {'id': 'gpt-4.1', 'name': 'GPT-4.1', 'provider': 'OpenAI', 'score': 88.2},
    {'id': 'claude-sonnet-3.7', 'name': 'Claude 3.7 Sonnet', 'provider': 'Anthropic', 'score': 86.4},
    {'id': 'qwen-long', 'name': '通义千问 Long', 'provider': '通义千问', 'score': 85.7},
    {'id': 'kimi-k2', 'name': 'Kimi K2', 'provider': 'Kimi', 'score': 84.9},
    {'id': 'glm-4-long', 'name': 'GLM-4 Long', 'provider': '智谱AI', 'score': 83.3},
    {'id': 'minimax-m3', 'name': 'MiniMax-M3', 'provider': 'MiniMax', 'score': 82.8},
    {'id': 'mimo-v2.5-pro', 'name': 'MiMo v2.5 Pro', 'provider': '小米 MiMo', 'score': 81.6},
    {'id': 'deepseek-v4-pro', 'name': 'DeepSeek V4 Pro', 'provider': 'DeepSeek', 'score': 80.4},
    {'id': 'grok-4-fast', 'name': 'Grok 4 Fast', 'provider': 'xAI', 'score': 79.2},
  ],
  'reasoning': [
    {'id': 'o3', 'name': 'o3', 'provider': 'OpenAI', 'score': 87.5},
    {'id': 'gemini-2.5-pro', 'name': 'Gemini 2.5 Pro', 'provider': 'Google', 'score': 86.8},
    {'id': 'claude-opus-4-5', 'name': 'Claude Opus 4.5', 'provider': 'Anthropic', 'score': 85.1},
    {'id': 'deepseek-r1', 'name': 'DeepSeek R1', 'provider': 'DeepSeek', 'score': 84.3},
    {'id': 'qwen3-max', 'name': 'Qwen3-Max', 'provider': '通义千问', 'score': 82.6},
    {'id': 'grok-4', 'name': 'Grok 4', 'provider': 'xAI', 'score': 82.1},
    {'id': 'glm-5.2', 'name': 'GLM-5.2', 'provider': '智谱AI', 'score': 80.7},
    {'id': 'kimi-k3', 'name': 'Kimi K3', 'provider': 'Kimi', 'score': 80.2},
    {'id': 'mimo-v2.5-pro', 'name': 'MiMo v2.5 Pro', 'provider': '小米 MiMo', 'score': 78.9},
    {'id': 'llama-4-maverick', 'name': 'Llama 4 Maverick', 'provider': 'Meta', 'score': 76.3},
  ],
  'value': [
    {'id': 'deepseek-v4-flash', 'name': 'DeepSeek V4 Flash', 'provider': 'DeepSeek', 'score': 0.8},
    {'id': 'glm-4.7-flash', 'name': 'GLM-4.7-Flash', 'provider': '智谱AI', 'score': 1.0},
    {'id': 'qwen-turbo', 'name': '通义千问 Turbo', 'provider': '通义千问', 'score': 1.2},
    {'id': 'gemini-2.5-flash', 'name': 'Gemini 2.5 Flash', 'provider': 'Google', 'score': 2.1},
    {'id': 'gpt-4o-mini', 'name': 'GPT-4o Mini', 'provider': 'OpenAI', 'score': 2.5},
    {'id': 'doubao-lite', 'name': 'Doubao Lite', 'provider': '火山引擎', 'score': 1.6},
    {'id': 'llama-3.3-70b-versatile', 'name': 'Llama 3.3 70B (Groq)', 'provider': 'Groq', 'score': 2.9},
    {'id': 'mistral-small-4', 'name': 'Mistral Small 4', 'provider': 'Mistral', 'score': 3.4},
    {'id': 'kimi-k2.6', 'name': 'Kimi K2.6', 'provider': 'Kimi', 'score': 4.0},
    {'id': 'claude-haiku-4.5', 'name': 'Claude Haiku 4.5', 'provider': 'Anthropic', 'score': 5.2},
  ],
  'chinese': [
    {'id': 'qwen3-max', 'name': 'Qwen3-Max', 'provider': '通义千问', 'score': 90.2},
    {'id': 'deepseek-v4-pro', 'name': 'DeepSeek V4 Pro', 'provider': 'DeepSeek', 'score': 89.6},
    {'id': 'kimi-k3', 'name': 'Kimi K3', 'provider': 'Kimi', 'score': 88.4},
    {'id': 'glm-5.2', 'name': 'GLM-5.2', 'provider': '智谱AI', 'score': 87.1},
    {'id': 'ernie-4.5-turbo', 'name': 'ERNIE 4.5 Turbo', 'provider': '文心一言', 'score': 85.8},
    {'id': 'doubao-2.1-pro', 'name': 'Doubao 2.1 Pro', 'provider': '火山引擎', 'score': 85.2},
    {'id': 'hunyuan-turbos', 'name': '混元-TurboS', 'provider': '腾讯混元', 'score': 84.5},
    {'id': 'spark-max', 'name': '星火 Max', 'provider': '讯飞星火', 'score': 82.7},
    {'id': 'minimax-m3', 'name': 'MiniMax-M3', 'provider': 'MiniMax', 'score': 82.1},
    {'id': 'SenseChat-5', 'name': '日日新 SenseChat 5', 'provider': '商汤', 'score': 80.6},
  ],
};

const Map<String, String> kLeaderboardNames = {
  'overall': '综合',
  'coding': '代码',
  'longctx': '长文本',
  'reasoning': '推理',
  'value': '性价比',
  'chinese': '中文',
};
